name: Ballerina build on PR and Merge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Ballerina Generate gRPC
        uses: ballerina-platform/ballerina-action@master
        with:
          args: 
            grpc 
            --input 
            modules/grpc_api/descriptor_record_store.proto
            --output 
            modules/grpc_api/
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args: 
            build
